// Generated by GraphWalker (http://www.graphwalker.org)
package com.company.models;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "com/company/models/VeterinariensSharedState.graphml")
public interface VeterinariensSharedState {

    @Edge()
    void e_Search();

    @Vertex()
    void v_SearchResult();

    @Vertex()
    void v_Veterinarians();
}
